### ISSUE TITLE
Clean up Navbar CSS to make it look like the mockups

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-ui#5]

**Comment by anilnatha** [comment]
Updated Styling:

Default:

<img width="1616" alt="image" src="https://github.com/unity-sds/unity-ui/assets/931107/e7611219-0a8c-4c97-b697-0ad6b9b7ed55">

Hover:

<img width="1616" alt="image" src="https://github.com/unity-sds/unity-ui/assets/931107/8784d1db-c3bd-4369-a032-ef48c815ab8f">

Mobile Menu:

<img width="562" alt="image" src="https://github.com/unity-sds/unity-ui/assets/931107/b29083b5-c3e2-4e5c-b958-b739f3feb85e">

**Comment by anilnatha** [comment]
PR issued, awaiting review.

**Comment by anilnatha** [comment]
Restyled border and caret. Had to adjust styling of caret due to limitations in react-stellar's implementation of the menu.

Below is a zoomed in view of the border and caret styling. As you can see the caret is no longer colored gray as it was in figma, instead I had to change it to white to work around the react-stellar implementation.

<img width="458" alt="image" src="https://github.com/unity-sds/unity-ui/assets/931107/55b921a8-d0f1-4949-83a4-87a85e4f984a">

**Comment by rtapella** [comment]
Closed. Made more like the Figma
